/**
 * TIO icon per admin menu item, matching the previous (6amMart) admin panel.
 * Items that exist there use its exact icon; Lagech-only items get the
 * closest TIO icon. Matched by label first, then by the menu's icon key.
 */
export const TIO_BY_LABEL = {
  // Food section, as on the old panel.
  Dashboard: "home-vs-1-outlined",
  "New Sale": "shopping-basket-outlined",
  Orders: "shopping-cart",
  "Order Refunds": "receipt",
  Campaigns: "layers-outlined",
  Banners: "image",
  "Other Banners": "image",
  Coupons: "gift",
  "Push Notification": "notifications",
  Advertisements: "tv-old",
  Advertisement: "tv-old",
  Reels: "video-camera-outlined",
  Categories: "category",
  Addons: "add-circle-outlined",
  "Food Setup": "premium-outlined",
  "New Restaurants": "calendar-note",
  "Add New Restaurant": "add-circle",
  Restaurants: "layout",
  "Restaurants List": "layout",
  "Recommended Restaurants": "hot",
  // Users section.
  Cashback: "settings-back",
  "Vehicles Category": "car",
  "Add Delivery Man": "running",
  "New Delivery Man": "man",
  "Deliveryman List": "filter-list",
  Reviews: "star-outlined",
  Customers: "poi-user",
  "Customer Wallet": "wallet",
  "Customer Loyalty Point": "medal",
  "Subscribed Mail List": "email-outlined",
  "Employee Roles": "incognito",
  Employees: "user",
  // Transactions & reports.
  "Withdraw Requests": "table",
  "Deliveryman Withdraws": "table",
  "Restaurant Disbursement": "wallet-outlined",
  "Delivery Man Disbursement": "saving-outlined",
  "Cash Limit Settlement": "money",
  "Delivery Man Payments": "send",
  "Restaurant Payments": "send",
  "Withdraw Method": "savings",
  "Transaction Report": "chart-pie-1",
  "Item Report": "chart-bar-1",
  "Restaurant Wise Report": "home",
  "Admin Earning Report": "money",
  "Restaurant Earning Report": "align-to-bottom",
  "Deliveryman Earning Report": "car",
  "Expense Report": "chart-line-down",
  "Disbursement Report": "saving",
  "Order Report": "chart-bar-4",
  "Tax Report": "albums",
  "Restaurant VAT Report": "american-express",
  // Lagech-only items.
  Dispatch: "bike",
  "Cancel Reasons": "clear-circle-outlined",
  "Order Detect Delivery": "map",
  "Referral Settings": "share-vs",
  "Zone Setup": "map-outlined",
  "Live Tracking": "map",
  "Duty Log": "history",
  "Earnings & Bonus": "dollar-outlined",
  "Cash & Wallet": "wallet",
  "Emergency Help": "warning-outlined",
  "Delivery Support Tickets": "support-vs",
  "Order Reassignment Requests": "refresh",
  "Live Chat": "chat-outlined",
  "Support Tickets": "ticket",
  "Contact Messages": "message-outlined",
  "Safety Emergency Reports": "warning-outlined",
  "Balance Sheet": "account-square-outlined",
  "Customer Feedback Report": "chart-donut-2",
  "Business Setup": "settings-outlined",
  "Feature Settings": "settings",
  "Power Scanning": "lock-outlined",
  "Business Pages": "pages-outlined",
  "Social Media": "share-vs",
  "Email Templates": "email-outlined",
}

/** Fallbacks by the menu's lucide icon key, for anything not named above. */
export const TIO_BY_ICON_KEY = {
  LayoutDashboard: "home-vs-1-outlined",
  CreditCard: "shopping-basket-outlined",
  FileText: "chart-bar-4",
  Receipt: "receipt",
  Truck: "bike",
  AlertTriangle: "warning-outlined",
  Image: "image",
  Megaphone: "tv-old",
  Camera: "video-camera-outlined",
  IndianRupee: "dollar-outlined",
  Gift: "gift",
  Bell: "notifications",
  FolderTree: "category",
  PlusCircle: "add-circle-outlined",
  Utensils: "premium-outlined",
  MapPin: "map-outlined",
  Store: "calendar-note",
  UtensilsCrossed: "layout",
  UserPlus: "man",
  Package: "filter-list",
  Star: "star-outlined",
  Clock: "history",
  PiggyBank: "wallet",
  Phone: "warning-outlined",
  MessageSquare: "chat-outlined",
  Users: "poi-user",
  Mail: "message-outlined",
  UserCog: "user",
  Lock: "incognito",
  Wallet: "table",
  Settings: "settings-outlined",
  Zap: "lock-outlined",
  Globe: "pages-outlined",
}

export const tioIconFor = (item) =>
  TIO_BY_LABEL[String(item?.label || "").trim()] || TIO_BY_ICON_KEY[item?.icon] || "circle"
